export const sources = {
  logo: {
    logoHorizonDark: 'assets/images/logo/logo-horizon-dark-mode.png',
    logoHorizonLight: 'assets/images/logo/logo-horizon-light-mode.png',
    logoSquareDark: 'assets/images/logo/logo-square-dark-mode.png',
    logoSquareLight: 'assets/images/logo/logo-square-light-mode.png',
    logoSmallDark: 'assets/images/logo/logo-small-dark-mode.png',
    logoSmallLight: 'assets/images/logo/logo-small-light-mode.png',
  },
  character: {
    egg: {
      bad: 'assets/images/character/egg-bad.png',
      normal: 'assets/images/character/egg-normal.png',
      special: 'assets/images/character/egg-special.png',
      superSpecial: 'assets/images/character/egg-super-special.png',
    },
    child: {
      child: 'assets/images/character/child-normal.png',
    },
    evolution: {
      mud: 'assets/images/character/evolution-mud.png',
      poinson: 'assets/images/character/evolution-poinson.png',
      burned: 'assets/images/character/evolution-burned.png',
      limbs: 'assets/images/character/evolution-limbs.png',
      strong: 'assets/images/character/evolution-strong.png',
      smooth: 'assets/images/character/evolution-smooth.png',
      carrot: 'assets/images/character/evolution-carrot.png',
      rainbow: 'assets/images/character/evolution-rainbow.png',
      glass: 'assets/images/character/evolution-glass.png',
      cute: 'assets/images/character/evolution-cute.png',
      monster: 'assets/images/character/evolution-monster.png',
      cat: 'assets/images/character/evolution-cat.png',
      fox: 'assets/images/character/evolution-fox.png',
      goose: 'assets/images/character/evolution-goose.png',
    },
    cooked: {
      mud: 'assets/images/character/cooked-mud.png',
      poison: 'assets/images/character/cooked-poison.png',
      burned: 'assets/images/character/cooked-burned.png',
      limbs: 'assets/images/character/cooked-limbs.png',
      strong: 'assets/images/character/cooked-strong.png',
      smooth: 'assets/images/character/cooked-smooth.png',
      carrot: 'assets/images/character/cooked-carrot.png',
      rainbow: 'assets/images/character/cooked-rainbow.png',
      glass: 'assets/images/character/cooked-glass.png',
      cute: 'assets/images/character/cooked-cute.png',
      monster: 'assets/images/character/cooked-monster.png',
      cat: 'assets/images/character/cooked-cat.png',
      fox: 'assets/images/character/cooked-fox.png',
      goose: 'assets/images/character/cooked-goose.png',
    },
    dead: {
      dead: 'assets/images/character/dead.png',
    },
    others: {
      isFreezing: 'assets/images/character/is-freezing.png',
      unlocked: 'assets/images/character/unlocked.png',
    }
  },
  store: {
    food: {
      worm: 'assets/images/store/worm.png',
      rice: 'assets/images/store/rice.png',
      chicken: 'assets/images/store/chicken.png',
      candy: 'assets/images/store/candy.png',
      fish: 'assets/images/store/fish.png',
      dogFood: 'assets/images/store/dog-food.png',
      icecream: 'assets/images/store/icecream.png',
    },
    health: {
      pill: 'assets/images/store/pill.png',
      ginseng: 'assets/images/store/ginseng.png',
      chineseMedicine: 'assets/images/store/chinese-medicine.png',
      pillForHeadache: 'assets/images/store/pill-for-headache.png',
      pillForDiarrhea: 'assets/images/store/pill-for-diarrhea.png',
      pillForGastricUlcer: 'assets/images/store/pill-for-gastric-ulcer.png',
      pillForFlu: 'assets/images/store/pill-for-flu.png',
      rebornPill: 'assets/images/store/reborn-pill.png',
      freezePill: 'assets/images/store/freeze-pill.png',
    },
    gifts: {
      doll: 'assets/images/store/doll.png',
      cellphone: 'assets/images/store/cellphone.png',
    },
    decorations: {
      star: 'assets/images/store/star.png',
    }
  },
  scene: {
    roomDayLightOn: 'assets/images/scene/room-day-light-on.jpg',
    roomDayLightOff: 'assets/images/scene/room-day-light-off.jpg',
    roomNightLightOn: 'assets/images/scene/room-night-light-on.jpg',
    roomNightLightOff: 'assets/images/scene/room-night-light-off.jpg',
  },
  bed: {
    bedEmptyLight: 'assets/images/bed/bed-empty-light.png',
    bedIsSleepingLight: 'assets/images/bed/bed-is-sleeping-light.png',
    bedEmptyDark: 'assets/images/bed/bed-empty-dark.png',
    bedIsSleepingDark: 'assets/images/bed/bed-is-sleeping-dark.png',
  },
  otherIcons: {
    coin: 'assets/images/other-icons/coin.png',
    store: 'assets/images/other-icons/store.png',
    lamp: 'assets/images/other-icons/lamp.png',
    dirty01: 'assets/images/other-icons/dirty01.png',
    dirty02: 'assets/images/other-icons/dirty02.png',
    dirty03: 'assets/images/other-icons/dirty03.png',
    collection: 'assets/images/other-icons/collection.png',
    feed: 'assets/images/other-icons/feed.png',
    sleep: 'assets/images/other-icons/sleep.png',
  },
  moodStatus: {
    isSleeping: 'assets/images/mood-status/is-sleeping.png',
    loving: 'assets/images/mood-status/loving.png',
    angry: 'assets/images/mood-status/loving.png',
    sad: 'assets/images/mood-status/loving.png',
  }
};
